//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestucture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnbezadoOrdenPedido
    {
        public int idOrdenPedido { get; set; }
        public Nullable<int> idMovimiento { get; set; }
        public int codPersona { get; set; }
        public string fecha { get; set; }
        public int estado { get; set; }
    
        public virtual DetalleOrdenPedido DetalleOrdenPedido { get; set; }
        public virtual movimientoTipo movimientoTipo { get; set; }
    }
}
